name: "🛠 Task"
description: "기능 외 작업(리팩터링·인프라·문서·테스트)"
title: "[ 페이지명 ] "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        제목은 `[ 페이지명 ] 내용` 형식으로 작성합니다. (예: `[ CI ] 파이프라인 캐시 적용`)
        **대괄호 안에 띄어쓰기가 있어요!**
  - type: textarea
    attributes:
      label: 🛠 어떤 작업인가요?
      description: 무엇을 할지 설명해 주세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: ✅ To Dos
      description: 할 일을 체크박스 형태로 적어주세요.
      value: |
        - [ ]
        - [ ]
        - [ ]
    validations:
      required: true
  - type: dropdown
    attributes:
      label: 📂 분류
      options:
        - 인프라
        - 문서
        - 테스트
        - 리팩터링
        - 기타
    validations:
      required: false
  - type: textarea
    attributes:
      label: 🙋🏻 참고 자료
      description: 참고 자료가 있다면 작성해 주세요.
