-- 은퇴한 시드. 내용은 rules/small-appliance/v1.yaml로 옮겼다.
--
-- 룰이 SQL INSERT 문자열 안에 있으면 커뮤니티가 git diff로 변경을 검토할 수 없다.
-- 이제 룰은 저장소 루트의 rules/에 YAML로 살고, 기동 시 RuleFileSyncRunner가 반영한다.
-- 스키마: schema/ruleset.schema.json · 검증: ./gradlew validateRules
--
-- 파일 자체를 지우지 않는 이유: 이미 이 마이그레이션을 적용한 DB에서 Flyway가
-- "적용된 마이그레이션이 로컬에 없다"며 검증에 실패하기 때문이다. 내용만 비운다.
