-- 은퇴한 시드. 내용은 weights/document-weights.yaml로 옮겼다.
--
-- 로딩 규칙은 그대로다: 없는 코드만 삽입하고 기존 행은 건드리지 않는다
-- (기존 ON CONFLICT DO NOTHING → RuleSetSyncPort.insertMissingWeights).
-- 관리자 API로 조정한 가중치가 재기동으로 되돌아가지 않게 하기 위함이다.
--
-- 사유와 배경은 R__seed_rules.sql 참조.
